"use client";
import {FormEvent,useEffect,useState} from "react";
import {Package,Plus,ShoppingCart,Users,RefreshCw} from "lucide-react";
type Item={itemId:string;name:string;category:string;stock:number;priceRwf:number};
type Customer={customerId:string;name:string;phone:string;email:string};
const fmt=(n:number)=>new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(n);
export default function BusinessTools(){
 const[items,setItems]=useState<Item[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[name,setName]=useState("");const[category,setCategory]=useState("General");const[stock,setStock]=useState("0");const[price,setPrice]=useState("1000");const[cName,setCName]=useState("");const[cPhone,setCPhone]=useState("");const[cEmail,setCEmail]=useState("");const[selected,setSelected]=useState("");const[qty,setQty]=useState("1");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
 async function load(){setError("");try{const [ir,cr]=await Promise.all([fetch("/api/inventory",{cache:"no-store"}),fetch("/api/customers",{cache:"no-store"})]);const id=await ir.json();const cd=await cr.json();if(!ir.ok)throw new Error(id.error||"Could not load inventory.");if(!cr.ok)throw new Error(cd.error||"Could not load customers.");setItems(id.items||[]);setCustomers(cd.customers||[]);if(!selected&&id.items?.[0])setSelected(id.items[0].itemId);}catch(e){setError(e instanceof Error?e.message:"Could not load business data.");}}
 useEffect(()=>{void load()},[]);
 async function addItem(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,category,stock:Number(stock),priceRwf:Number(price)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not add item.");setName("");setStock("0");setNotice("Inventory item saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not save item.");}finally{setBusy(false)}}
 async function addCustomer(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:cName,phone:cPhone,email:cEmail})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not add customer.");setCName("");setCPhone("");setCEmail("");setNotice("Customer saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not save customer.");}finally{setBusy(false)}}
 async function createSale(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:[{itemId:selected,quantity:Number(qty)}]})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not record sale.");setNotice("Sale recorded. Share this order reference with the customer: "+d.order.orderId);await load();}catch(e){setError(e instanceof Error?e.message:"Could not record sale.");}finally{setBusy(false)}}
 return <section className="business-tools"><div className="business-tools-heading"><div><span className="section-kicker">LIVE BUSINESS DATA</span><h2>Manage your business</h2><p>These forms save data to your signed-in business account.</p></div><button className="payment-refresh" onClick={()=>void load()} aria-label="Refresh business data"><RefreshCw size={15}/></button></div>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="business-notice" role="status">{notice}</p>}
 <div className="business-tools-grid"><form className="business-tool-card" onSubmit={addItem}><Package size={20}/><h3>Add inventory item</h3><label>Item name<input required minLength={1} maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Rice 5kg"/></label><label>Category<input maxLength={80} value={category} onChange={e=>setCategory(e.target.value)} placeholder="Groceries"/></label><div className="business-form-row"><label>Opening stock<input type="number" min="0" step="1" required value={stock} onChange={e=>setStock(e.target.value)}/></label><label>Price (RWF)<input type="number" min="0" step="1" required value={price} onChange={e=>setPrice(e.target.value)}/></label></div><button className="marketing-button" disabled={busy}><Plus size={14}/> Save item</button></form>
 <form className="business-tool-card" onSubmit={createSale}><ShoppingCart size={20}/><h3>Record a sale</h3><label>Item<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select inventory item</option>{items.map(i=><option key={i.itemId} value={i.itemId}>{i.name} · {i.stock} in stock · {fmt(i.priceRwf)}</option>)}</select></label><label>Quantity<input type="number" min="1" max="100000" step="1" required value={qty} onChange={e=>setQty(e.target.value)}/></label><p className="business-tool-help">The server checks available stock and calculates the total. The resulting order reference is used for customer payment.</p><button className="marketing-button" disabled={busy||!items.length}><ShoppingCart size={14}/> Record sale</button></form>
 <form className="business-tool-card" onSubmit={addCustomer}><Users size={20}/><h3>Add customer</h3><label>Customer name<input required minLength={2} maxLength={100} value={cName} onChange={e=>setCName(e.target.value)} placeholder="Full name"/></label><label>Phone<input maxLength={20} value={cPhone} onChange={e=>setCPhone(e.target.value)} placeholder="07xxxxxxxx"/></label><label>Email<input type="email" maxLength={254} value={cEmail} onChange={e=>setCEmail(e.target.value)} placeholder="Optional email"/></label><button className="marketing-button" disabled={busy}><Plus size={14}/> Save customer</button><p className="business-tool-help">{customers.length} customer(s) saved to this business.</p></form></div></section>
}
