"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {MarketingLayout} from "../components/marketing";
export default function SignupPage(){
 const router=useRouter();const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[role,setRole]=useState("trader");const[businessName,setBusinessName]=useState("");const[businessType,setBusinessType]=useState("Retail shop");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password,role,businessName,businessType})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create account.");router.push(role==="customer"?"/payments":"/workspace");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not create account.");}finally{setBusy(false)}}
 return <MarketingLayout><main className="auth-page"><form className="auth-card" onSubmit={submit}><span className="section-kicker">GET STARTED</span><h1>Create your account</h1><p>Your own secure EasyPay Rwanda workspace.</p><label htmlFor="name">Full name</label><input id="name" autoComplete="name" minLength={2} maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" maxLength={254} required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="role">Account type</label><select id="role" value={role} onChange={e=>setRole(e.target.value)}><option value="trader">Trader / business owner</option><option value="customer">Customer</option></select>{role==="trader"&&<><label htmlFor="businessName">Business name</label><input id="businessName" required minLength={2} maxLength={100} value={businessName} onChange={e=>setBusinessName(e.target.value)}/><label htmlFor="businessType">Business type</label><select id="businessType" value={businessType} onChange={e=>setBusinessType(e.target.value)}><option>Retail shop</option><option>Restaurant</option><option>Pharmacy</option><option>Services</option><option>Wholesale</option><option>Other</option></select></>}<label htmlFor="password">Password (at least 10 characters)</label><input id="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="marketing-button auth-submit" disabled={busy}>{busy?"Creating account…":"Create account"}</button><p className="auth-switch">Already registered? <Link href="/login">Sign in</Link></p></form></main></MarketingLayout>
}
